version: 2
jobs:
  build:
    machine:
      image: cimg/base:2020.07-20.04
    
    steps:
      - run:
          name: Install & Sign Kali Repos
          command: wget -q -O - archive.kali.org/archive-key.asc | sudo apt-key add
      - run: sudo apt update
      - run: 
          name: Download Sifter
          command: |
            sudo git clone https://github.com/s1l3nt78/sifter.git /opt/sifter
      - run:
          name: Install Sifter
          command: | 
            cd /opt/sifter
            sudo bash install.sh
      - run:
          name: Run Sifter
          command: |
            bash /opt/sifter/sifter
     
