version: 2
jobs:
  build:
    docker:
      - image: s1l3nt78/sifter:build1
     steps:
      - checkout
      - run: mkdir /opt/
      - run: 
        name: Download Sifter
        command: |
            sudo git clone https://github.com/s1l3nt78/sifter.git /opt/sifter
      - run:
        name: Install Sifter
        command: | 
            cd /opt/sifter
            sudo bash install.sh
      - run:
        name: Run Sifter
        command: |
            bash /opt/sifter/sifter
     