version: 2
jobs:
  build:
    branches:
      only:
        - circleci-project-setup

    machine:
      image: ubuntu-1604:201903-01
      environment:
        DEBIAN_FRONTEND: noninteractive

    steps:
      #- restore_cache:
      #    key: deps1-{{ .Branch }}-{{ checksum "/opt/sifter/install.sh" }}
      - run: 
          name: Install & Sign Kali Repos
          command: |
            sudo sh -c "echo 'deb https://http.kali.org/kali kali-rolling main non-free contrib' > /etc/apt/sources.list.d/kali.list"
            sudo apt install gnupg
            wget 'https://archive.kali.org/archive-key.asc'
            sudo apt-key add archive-key.asc
    
      - run: 
          name: Remove Unnecessary Repos
          command: | 
            sudo rm /etc/apt/sources.list.d/google-chrome.list /etc/apt/sources.list.d/heroku.list
  
  # Update System Repos & Apt Deps
      - run: sudo apt update
      - run: echo '* libraries/restart-without-asking boolean true' | sudo debconf-set-selections
      - run: sudo apt-get update
      - run: sudo apt-get install python3.8 python3-pip

      - run:
          name: Python Version Links
          command: |
            ls /usr/bin/python
            #sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
            sudo update-alternatives --install /usr/bin/python3 python3.8 /usr/bin/python3.8 1
            
  # Update System Packages
      #- run: yes | sudo apt full-upgrade
  
      - run: 
          name: Download Sifter
          command: |
            sudo git clone https://github.com/s1l3nt78/sifter.git /opt/sifter
      
      - run:
          name: Arg Replacements
          command: | 
            cd /opt/sifter
            OUT='read INSTALL_PROMPT'
            INS='#read INSTALL_PROMPT'
            sudo sed -i "s/${OUT}/${INS}/g" install.sh
            OSOUT='read INOPT'
            OSIN='l | read INOPT'
            sudo sed -i "s/${OSOUT}/${OSIN}/g" install.sh

            #UPO='sudo ./install-perl-module.sh'
            #UPI='#sudo ./install-perl-module.sh'
            #sudo sed -i "s/${UPO}/${UPI}/g" install.sh
      
      - run: 
          name: Pip2 Updates
          command: |
            sudo pip2 install --upgrade pip 
            pip2 install --upgrade pip 
            sudo pip2 install setuptools wheel
            
      #- run:
      #    name: Pip3 Updates
      #    command: |
      #      sudo python3 -m pip install --upgrade pip 
      #      python3 -m pip install --upgrade pip 
      #      #sudo pip3 install setuptools wheel

      - run: sudo bash /opt/sifter/install.sh
      - run:
          name: Run Sifter
          command: |
            bash /opt/sifter/sifter
      
      #- save_cache:
      #    key: deps1-{{ .Branch }}-{{ checksum "/opt/sifter/install.sh" }}
      #    paths:
      #      - "/opt"
