version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    
    steps:
      - checkout
      - run: 
          name: Download Sifter
          command: |
            sudo git clone https://github.com/s1l3nt78/sifter.git /opt/sifter
      - run:
          name: Install Sifter
          command: | 
            cd /opt/sifter
            sudo bash install.sh
      - run:
          name: Run Sifter
          command: |
            bash /opt/sifter/sifter
     
