version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      environment:
        DEBIAN_FRONTEND: noninteractive

    steps:
      - run: 
          name: Install & Sign Kali Repos
          command: |
            sudo sh -c "echo 'deb https://http.kali.org/kali kali-rolling main non-free contrib' > /etc/apt/sources.list.d/kali.list"
            sudo apt install gnupg
            wget 'https://archive.kali.org/archive-key.asc'
            sudo apt-key add archive-key.asc
    
    - run: 
          name: Remove Unnecessary Repos
          command: | 
            sudo rm /etc/apt/sources.list.d/google-chrome.list /etc/apt/sources.list.d/heroku.list
  
  # Update System Repos
      - run: sudo apt update
  
  # Update System Packages
      #- run: yes | sudo apt full-upgrade
  
  - run: 
          name: Download Sifter
          command: |
            sudo git clone https://github.com/s1l3nt78/sifter.git /opt/sifter
      - run:
          name: Arg Replacements
          command: | 
            cd /opt/sifter
            OUT='read INSTALL_PROMPT'
            INS='#read INSTALL_PROMPT'
            sudo sed -i "s/${OUT}/${INS}/g" install.sh
            OSOUT='read INOPT'
            OSIN='l | read INOPT'
            sudo sed -i "s/${OSOUT}/${OSIN}/g" install.sh
            echo '* libraries/restart-without-asking boolean true' | sudo debconf-set-selections
         #UPO='sudo apt full-upgrade'
         #UPI='yes | sudo apt full-upgrade'
         #sudo sed -i "s/${UPO}/${UPI}/g" install.sh
      - run: sudo bash /opt/sifter/install.sh
      - run:
          name: Run Sifter
          command: |
            bash /opt/sifter/sifter
     
