version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    
    steps:
      - run: sudo sed -i "s/""/\"deb http://http.kali.org/kali kali-rolling main non-free contrib\"/g" /etc/apt/sources.list
      - run:
          name: Install & Sign Kali Repos
          command: wget -q -O - archive.kali.org/archive-key.asc | sudo apt-key add
      - run: sudo rm /etc/apt/sources.list.d/google-chrome.list /etc/apt/sources.list.d/heroku.list
      - run: sudo apt update
      - run: 
          name: Download Sifter
          command: |
            sudo git clone https://github.com/s1l3nt78/sifter.git /opt/sifter
      - run:
          name: Install Sifter
          command: | 
            cd /opt/sifter
            sudo bash install.sh
            \n
            l
            l
            y
      - run:
          name: Run Sifter
          command: |
            bash /opt/sifter/sifter
     
